# 线上配置文件
server:
  port: 8101
spring:
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.104.147:3306/anti_fraud
    username: anti_fraud
    password: 261615
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # Redis 配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000